### Python

- Loop 
- Lists (ArrayLists)
- Dictionaries (HashMaps)

#### 1)  Write a function that returns the elements on odd positions (0 based) in a list


In [130]:
#def solution(input):
#    #code goes here 
#    return output
#
#assert solution([0,1,2,3,4,5]) == [1,3,5]
#assert solution([1,-1,2,-2]) == [-1,-2]


# 1st way
def solution1(x):
    return x[1::2]

# 2nd way
def solution2(x):
    l=[]
    for count, i in enumerate(x):
        if count % 2 == 1:
            l.append(i)
    return l 

def solution2_(x):
    return [i for count,i in enumerate(x) if count%2 == 1 ]

In [126]:
l = [0,1,2,3,4,5]
k = [1,-1,2,-2]
g = [-2, -4, -5, 10, 11, 99]

In [121]:
print (solution1(l))
print (solution1(k))
print (solution1(g))

[1, 3, 5]
[-1, -2]
[-4, 10, 99]


In [124]:
print (solution2(l))
print (solution2(k))
print (solution2(g))

[1, 3, 5]
[-1, -2]
[-4, 10, 99]


#### 2) Write a function that returns the cumulative sum of elements in a list

In [139]:
#def solution(input):
#    # Code goes here 
#    return output
#assert solution([1,1,1]) == [1,2,3]
#assert solution([1,-1,3]) == [1,0,3]

# 1st way 
def solution1(x):
    temp = 0 
    outcome = []
    for k in range(len(x)):
        temp += x[k]
        outcome.append(temp)
    return outcome

# 2nd way
def solution2(x):
    import numpy as np
    return np.cumsum(x)

# 3rd way 
from itertools import accumulate
def solution3(x):
    return list(accumulate(x))

In [140]:
l = [1,1,1]
k = [1,-1,3]
j = [0,-1,99]

In [6]:
print (solution1(l))
print (solution1(k))
print (solution1(j))

[1, 2, 3]
[1, 0, 3]
[0, -1, 98]


In [138]:
print (solution2(l))
print (solution2(k))
print (solution2(j))

[1 2 3]
[1 0 3]
[ 0 -1 98]


In [142]:
print (solution3(l))
print (solution3(k))
print (solution3(j))

[1, 2, 3]
[1, 0, 3]
[0, -1, 98]


#### 3) Write a function that takes a number and returns a list of its digits

In [166]:
#def solution(input):
#    # Code goes here
#    return output
#
#assert solution(123) == [1,2,3]
#assert solution(400) == [4,0,0]


# 1st way
def solution1(n):
    return [int(y) for y in str(n)]

# 2nd way 
def solution2(n):
    if n < 10:
        return [n]
    return solution2(int(n/10)) + [n%10]

# 3rd way
def solution3(n):
    return [int(y) for y in list(str(n))]
    #return list(map(int,str(x)))


In [144]:
print (solution1(133))
print (solution1(913))
print (solution1(3))

[1, 3, 3]
[9, 1, 3]
[3]


In [145]:
print (solution2(133))
print (solution2(913))
print (solution2(3))

[1, 3, 3]
[9, 1, 3]
[3]


#### 4) Return the "centered" average of an array of ints, which we'll say is  the mean average of the values, except ignoring the largest and  smallest values in the array.

In [207]:
#If there are multiple copies of the 
#smallest value, ignore just one copy, and likewise for the largest 
#value. Use int division to produce the final average. You may assume 
#that the array is length 3 or more.

#def solution(input):
#    # Code goes here
#    return output 

#assert solution([1, 2, 3, 4, 100]) == 3
#assert solution([1, 1, 5, 5, 10, 8, 7]) == 5
#assert solution([-10, -4, -2, -4, -2, 0]) == -3

# 1st way 
def solution1(x):
    length = len(x)
    if length%2 == 1:
        return x[int((length-1)/2)]
    if len(x)%2 == 0: 
        return (x[int((length-1)/2)] + x[int((length+1)/2)])/2
        

def solution3(nums):
    nums = set(nums)
    nums = sorted(nums)  # if input is not always sorted
    if len(nums) <= 2 :
        return sum(nums) / len(nums)
    nums1 = nums[1:-1]
    return sum(nums1) / len(nums1)



In [209]:
print (solution3(x)) 
print (solution3(y)) 
#print (solution3(z)) 
print (solution3(w)) 
print (solution3(k)) 

3.0
-3.0
50.0
4.0


In [183]:
x = [1, 2, 3, 4, 100]
y = [-10, -4, -2, -4, -2, 0]
z = [1, 1, 5, 5, 10, 8, 7]
w = [0,100]
k = [4]

print (solution1(x)) 
print (solution1(y)) 
print (solution1(z)) 
print (solution1(w)) 
print (solution1(k)) 

3
-3.0
5
50.0
4


#### 5)  Count distinct words in a sentence 

In [288]:
sentence = """But soft what light through yonder window breaks
It is the east and Juliet is the sun
Arise fair sun and kill the envious moon
Who is already sick and pale with grief
"""

sentence2= """But soft soft soft soft But envious"""

# 1st way 
def solution1(x):
    list_ = x.replace("\n","").split(" ")
    return set(list_)


# 2nd way 
def solution2(x):
    list_ = x.replace("\n","").split(" ")
    output = []
    for item in list_:
        if item in output:
            pass 
        else:
            output.append(item)
    return output 


In [291]:
solution2(sentence2)

['But', 'soft', 'envious']

In [286]:
solution1(sentence2)

{'But', 'envious', 'soft'}

#### 6) Count the number of times a word appear in a sentence using a Hash Map

In [263]:
sentence = """But soft what light through yonder window breaks
It is the east and Juliet is the sun
Arise fair sun and kill the envious moon
Who is already sick and pale with grief
"""

sentence2= """But soft soft soft soft But envious"""

# 1st way 
def solution1(x):
    count =[]
    list_ = x.replace("\n","").split(" ") 
    for item in set(list_):
        #print (item, list_.count(item) )
        count.append(list_.count(item))
        d = dict(zip(set(list_),count ))
    return d 

# 2nd way 
def solution2(x):
    from collections import Counter
    list_ = x.replace("\n","").split(" ") 
    counter = Counter(list_)
    for item in set(list_):
        print (item, counter[item])

# 3rd way         
def solution3(x):
    counts = dict()
    words = x.replace("\n","").split(" ") 

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

In [280]:
#d = dict({'a':1,'b':2})
# 1 in d.values()
# a in d 
# a in d.keys()
# d.items()

In [281]:
solution3(sentence2)

{'But': 2, 'envious': 1, 'soft': 4}

In [259]:
solution2(sentence2)

soft 4
But 2
envious 1


In [266]:
solution1(sentence)

{'But': 1,
 'Juliet': 1,
 'already': 1,
 'and': 3,
 'breaksIt': 1,
 'east': 1,
 'envious': 1,
 'fair': 1,
 'grief': 1,
 'is': 3,
 'kill': 1,
 'light': 1,
 'moonWho': 1,
 'pale': 1,
 'sick': 1,
 'soft': 1,
 'sun': 1,
 'sunArise': 1,
 'the': 3,
 'through': 1,
 'what': 1,
 'window': 1,
 'with': 1,
 'yonder': 1}

####  7)  Return tuples of a list, matching each item to another item

#### 8) Count the number of times a substring appear in a string


In [315]:
s = 'xyzbobxyzbobxyzbob'

# 1st way 
def solution1(x,substring):
    return x.count(substring)

# 2nd way 
def solution2(x,substring):
    results = 0
    sub_len = len(substring)
    for i in range(len(x)):
        if x[i:i+sub_len] == substring:
            results += 1
    print (results)

In [318]:
solution2(s,'bib')

0


In [303]:
solution1(s,'xyz')

3

In [ ]:
#########

### SQL

In [14]:
import pandas as pd 

from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [15]:
# df1 
salesperson = pd.DataFrame({'id':[1,2,5,7,8,11],
                            'Name':['abe','bob','chris','dan','ken','joe'],
                            'age':[61,34,34,41,57,38],
                            'salary':[140000,44000,40000,52000,115000,38000]})
# df2 
customer = pd.DataFrame({'id':[4,6,7,9], 
                         'Name':['samsonic','pansung','samony','orange'],
                         'city':['pleasant','oaktown','jackson','jackson'],
                         'industry_type':['J','J','B','B']})



# df3 
orders = pd.DataFrame({'number':[10,20,30,40,50,60,70],
                       'order_date':['8/2/96','1/30/99','7/14/95','1/29/98','2/3/98','3/2/98','5/6/98'],
                       'cust_id':[4,4,9,7,6,6,9],
                       'sales_person_id':[2,8,1,2,7,7,7],
                       'amount':[540,1800,460,2400,600,720,150]})

In [16]:
salesperson

Name  age  id  salary
0    abe   61   1  140000
1    bob   34   2   44000
2  chris   34   5   40000
3    dan   41   7   52000
4    ken   57   8  115000
5    joe   38  11   38000

In [17]:
customer

Name      city  id industry_type
0  samsonic  pleasant   4             J
1   pansung   oaktown   6             J
2    samony   jackson   7             B
3    orange   jackson   9             B

In [18]:
orders

amount  cust_id  number order_date  sales_person_id
0     540        4      10     8/2/96                2
1    1800        4      20    1/30/99                8
2     460        9      30    7/14/95                1
3    2400        7      40    1/29/98                2
4     600        6      50     2/3/98                7
5     720        6      60     3/2/98                7
6     150        9      70     5/6/98                7

#### a) The names of all salespeople that have an order with Samsonic. 

In [19]:
sql_a = """

select 
s.name 
from 
salesperson s 
left join orders o
on s.id = o.sales_person_id
where o.cust_id in (select id from customer where name = 'samsonic')

"""


In [20]:
pysqldf(sql_a)

Name
0  bob
1  ken

#### b) The names of all salespeople that do not have any order with Samsonic

In [21]:
sql_b = """

select 
name, count(name) from (
select 
s.name  as name 
from 
salesperson s 
left join orders o
on s.id = o.sales_person_id
where o.cust_id not in (select id from customer where name = 'samsonic')
) sub 
group by 1 

"""


In [22]:
pysqldf(sql_b)

name  count(name)
0  abe            1
1  bob            1
2  dan            3

#### c) The names of salespeople that have 2 or more orders. 

In [23]:
sql_c = """


select 
s.name as name,
count(s.name) as ordercount
from 
salesperson s 
left join orders o
on s.id = o.sales_person_id
group by 1
having ordercount >= 2 


"""


In [24]:
pysqldf(sql_c)

name  ordercount
0  bob           2
1  dan           3

#### d) The names and ages of all salespersons must having a salary of 100,000 or greater.



In [28]:
sql_d = """

select 
Name,
age,
salary
from 
salesperson
where salary >= 100000

"""


In [29]:
pysqldf(sql_d)

Name  age  salary
0  abe   61  140000
1  ken   57  115000

#### e) What sales people have sold more than 1400 total units?


In [55]:
sql_e = """

with 
amount
as 
(select 
sales_person_id as id,
sum(amount) as sale_amount
from  
orders 
group by 1 
having  sale_amount >= 1400 ) 

select 
s.*,
a.sale_amount
from 
salesperson s 
inner join  amount  a 
on a.id = s.id



"""

In [56]:
pysqldf(sql_e)

Name  age  id  salary  sale_amount
0  bob   34   2   44000         2940
1  dan   41   7   52000         1470
2  ken   57   8  115000         1800

#### f)  When was the earliest and latest order made to Samony?


In [60]:
sql_f = """

select 
min(order_date) as min_date,
max(order_date) as max_date
from 
orders 
where cust_id = (select id from customer where name = 'samony' )



"""

In [61]:
pysqldf(sql_f)

min_date max_date
0  1/29/98  1/29/98